### ISSUE TITLE
Loading schematics into kiCad

### ISSUE THREAD

**Issue by suenio** [trycoon/liam-esp#7]
I downloaded repository files from github and wonted to open schematics in KiCad however when doing it KiCad shows missing library. Any hint how to fix this?

BTW: great work on this lawn mower software and hardware !!!

**Comment by trycoon** [comment]
Hi!
Well that's the problem with softwares you install on your computer I guess, once you get everything up and running you have to write a manual for others (or if ever you need to reinstall your computer). I actually looked at https://easyeda.com, which is cloud-based, but I didn't have time or motivation to put into the effort moving from KiCAD. Maybe in the future.
I made a new push, can you verify if you could open the project now? I also made a PDF of the schematics for those that don't want to bother with KiCAD: https://github.com/trycoon/liam-esp/blob/master/hardware/schematic/liam-esp.pdf
The project is still very much a work in progress, I'm hoping for something more complete and stabilised to the next summer, and then a PCB in PDF and KiCAD should also be in place.

**Comment by suenio** [comment]
Hi Henrik,
Thank you for response. I finally managed to find some tiem to reconfigure
PlatformIO however using git repo and following instruction in there I cant
compile due to some errors. Did you do any fixes or manual changes within
AsyncTCP and Async MQTT libraries after pulling them from git? Problems are
due to fact esp32 is using different esp core implementation than esp8266.

Thanx,
Wojtek

**Comment by trycoon** [comment]
No, I have not done any changes to Async MQTT or AsyncTCP, just use the ones specified in platform.ini: https://github.com/trycoon/liam-esp/blob/master/platformio.ini#L49
The correct versions should be downloaded when you build the project.
What compilation errors do you get?

I'm currently working on a BIG rewrite of the software and hardware, I'm exploring the https://github.com/trycoon/liam-esp/issues/6. If that is not what you want then fork the "esp-wifi" branch, since the Master branch will later have no/very little WiFi code (not using AsyncTCP) since communication is done over LoRa radio. If everything works out as I'm hoping for.

**Comment by suenio** [comment]
I think thats great idea. As soon as I will be done with my commitments
today I plan to start contributing to your project. Need to revamp my
current automower to something opensourced ;)

**Comment by kkszysiu** [comment]
Sadly KiCad doesn't work for me as well.

It seems that some of the symbols you're using in your project are not included into KiCad schematics.

@trycoon , will you be able to share whole KiCad schematics? Or at least Gerber files?

**Comment by trycoon** [comment]
Hi! This is still very much a project still in development, I change thing all the time. If that's fine by you the you are welcome to tag along, otherwise maybe the original Liam och Ardumower-projects are better suited for you (they are more mature and stable).
That being said, I have since a while back switched from KiCad to the online editor EasyEDA, it just makes it easier to share and collaborate around a Open Source project!
Revisit this page for more up-to-date schematics and instructions: https://github.com/trycoon/liam-esp/tree/master/hardware

**Comment by trycoon** [comment]
This season I will focus mostly on 3D printing to mower body, the electronics, and maybe the software of the docking station. In winter the mower firmware will be updated to work with the new hardware and the docking station.

**Comment by kkszysiu** [comment]
@trycoon , no worries. I want to help. I'm just more a developer than hardware designer, so the latter is sometimes kind of troublesome to me :)

Thank you for fresh links! Last time I was checking there were only KiCad files.

**Comment by Plaethe** [comment]
Is this project still alive?
